# Generated by Django 3.1.1 on 2021-04-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_auto_20210201_0811'),
        ('subscription', '0004_auto_20210405_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontransaction',
            name='amount',
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(help_text='the name of the subscription plan', max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='planquota',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_quotas', to='subscription.plan'),
        ),
        migrations.AlterUniqueTogether(
            name='planquota',
            unique_together={('plan', 'quota')},
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Features', to='company.company')),
                ('plan_quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.planquota')),
            ],
            options={
                'unique_together': {('plan_quota', 'company')},
            },
        ),
    ]
