# Generated by Django 3.1.1 on 2021-03-05 15:26

import bat.autoemail.models
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0029_auto_20210201_0811'),
        ('setting', '0012_auto_20210122_1602'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('subject', models.CharField(max_length=512, verbose_name='Subject')),
                ('logo', models.ImageField(blank=True, upload_to=bat.autoemail.models.template_logo_name, verbose_name='Logo')),
                ('attachment_file', models.FileField(blank=True, upload_to=bat.autoemail.models.attachment_file_name, verbose_name='Attachment File')),
                ('language', models.CharField(choices=[('English', 'English'), ('German', 'German'), ('Italian', 'Italian')], default='English', max_length=50, verbose_name='Language')),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('channel', multiselectfield.db.fields.MultiSelectField(choices=[('FBA', 'FBA'), ('FBM', 'FBM')], max_length=50, verbose_name='Channel')),
                ('schedule', models.CharField(choices=[('Daily', 'Daily'), ('As soon as possible', 'As soon as possible')], default='Daily', max_length=50, verbose_name='Schedule')),
                ('schedule_time', models.TimeField(default=django.utils.timezone.now)),
                ('schedule_days', models.PositiveIntegerField(default=1)),
                ('buyer_purchase_count', multiselectfield.db.fields.MultiSelectField(choices=[('1st Purchase', '1st Purchase'), ('1nd Purchase', '1nd Purchase'), ('3rd Purchase', '3rd Purchase'), ('4th Purchase', '4th Purchase')], max_length=100, verbose_name="Buyer's Purchase Count")),
                ('exclude_orders', multiselectfield.db.fields.MultiSelectField(choices=[('Negative Feedback(1 star)', 'Negative Feedback(1 star)'), ('Negative Feedback(2 star)', 'Negative Feedback(2 star)'), ('Neutral Feedback(3 star)', 'Neutral Feedback(3 star)'), ('Positive Feedback(4 star)', 'Positive Feedback(4 star)'), ('Positive Feedback(5 star)', 'Positive Feedback(5 star)'), ('With Returns', 'With Returns'), ('With Refunds', 'With Refunds')], max_length=100, verbose_name='Exclude Orders')),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amazonmarketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.amazonmarketplace')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('emailtemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoemail.emailtemplate')),
                ('order_status', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='emailcampaign_order_status', to='setting.status')),
                ('status', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='emailcampaign_status', to='setting.status')),
            ],
        ),
    ]
