# Generated by Django 3.1.1 on 2021-04-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqueue',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
