# Generated by Django 3.1.1 on 2021-03-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='content',
            new_name='template',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='default_cc',
            field=models.CharField(blank=True, max_length=2096, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
