# Generated by Django 3.1.1 on 2021-03-08 14:43

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_amazonorder_amazonorderitem_amazonordershipping_amazonproduct'),
        ('autoemail', '0002_auto_20210306_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.CharField(max_length=512, verbose_name='Sent to Email')),
                ('sent_from', models.CharField(max_length=512, verbose_name='Sent from Email')),
                ('subject', models.CharField(max_length=512, verbose_name='Subject')),
                ('template', models.TextField()),
                ('is_queued', models.BooleanField(default=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amazonorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.amazonorder', verbose_name='Select Order')),
                ('emailcampaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoemail.emailcampaign')),
            ],
        ),
    ]
