# Generated by Django 3.1.1 on 2021-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemail', '0002_auto_20210402_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='include_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalemailcampaign',
            name='include_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
