# Generated by Django 3.1.1 on 2021-03-08 15:26

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('autoemail', '0003_emailqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='buyer_purchase_count',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1st Purchase', '1st Purchase'), ('1nd Purchase', '1nd Purchase'), ('3rd Purchase', '3rd Purchase'), ('4th Purchase', '4th Purchase')], max_length=512, verbose_name="Buyer's Purchase Count"),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='exclude_orders',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Negative Feedback(1 star)', 'Negative Feedback(1 star)'), ('Negative Feedback(2 star)', 'Negative Feedback(2 star)'), ('Neutral Feedback(3 star)', 'Neutral Feedback(3 star)'), ('Positive Feedback(4 star)', 'Positive Feedback(4 star)'), ('Positive Feedback(5 star)', 'Positive Feedback(5 star)'), ('With Returns', 'With Returns'), ('With Refunds', 'With Refunds')], max_length=512, verbose_name='Exclude Orders'),
        ),
    ]
