# Generated by Django 3.1.1 on 2021-04-12 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_auto_20210122_1602'),
        ('autoemail', '0003_auto_20210408_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emailcampaign_order_status', to='setting.status'),
        ),
        migrations.AlterField(
            model_name='globalemailcampaign',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='globalemailcampaign_order_status', to='setting.status'),
        ),
    ]
