# Generated by Django 3.1.1 on 2021-03-08 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoemail', '0004_auto_20210308_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='schedule_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
