# Generated by Django 3.1.1 on 2021-04-16 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoemail', '0004_auto_20210412_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='activation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
