# Generated by Django 3.1.1 on 2021-03-09 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_auto_20210122_1602'),
        ('autoemail', '0005_emailqueue_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailqueue',
            name='is_queued',
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='email_queue', to='setting.status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autoemail.emailtemplate'),
        ),
    ]
