# Generated by Django 3.1.1 on 2021-05-05 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoemail', '0005_emailcampaign_activation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesEmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('subject', models.CharField(max_length=512, verbose_name='Subject')),
                ('sent_from', models.CharField(max_length=512)),
                ('language', models.CharField(choices=[('English', 'English'), ('German', 'German'), ('Italian', 'Italian')], default='English', max_length=50, verbose_name='Language')),
                ('template', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('success_redirect', models.CharField(max_length=512)),
                ('error_redirect', models.CharField(max_length=512)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
