# Generated by Django 3.1.1 on 2021-05-05 09:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_amazonaccountcredentails_email_verified'),
        ('autoemail', '0006_sesemailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesEmailTemplateMarketPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amazonmarketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.amazonmarketplace')),
                ('sesemailtemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoemail.sesemailtemplate')),
            ],
        ),
    ]
