# Generated by Django 3.1.1 on 2021-05-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("autoemail", "0007_sesemailtemplatemarketplace")]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="globalemailtemplate",
            name="template",
            field=models.TextField(),
        ),
    ]
