# Generated by Django 3.1.1 on 2021-03-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemail', '0007_auto_20210316_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='send_date',
            field=models.DateTimeField(null=True),
        ),
    ]
