# Generated by Django 3.1.1 on 2021-05-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemail', '0008_auto_20210510_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='globalemailtemplate',
            name='template',
            field=models.TextField(),
        ),
    ]
