# Generated by Django 3.1.1 on 2021-05-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemail', '0010_auto_20210525_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='schedule_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
