# Generated by Django 3.1.1 on 2021-05-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoemail', '0011_auto_20210525_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='send_optout',
            field=models.BooleanField(default=False),
        ),
    ]
