# Generated by Django 3.1.2 on 2020-11-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytype',
            name='category',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='companytype_company', to='setting.category'),
            preserve_default=False,
        ),
    ]
