# Generated by Django 3.1.1 on 2020-11-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201110_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sv', 'Swedish')], default='en-us', max_length=50, verbose_name='Language'),
        ),
    ]
