# Generated by Django 3.1.2 on 2020-11-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companytype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypaymentterms',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Deposit (in %)'),
        ),
        migrations.AlterField(
            model_name='companypaymentterms',
            name='on_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Payment on delivery (in %)'),
        ),
        migrations.AlterField(
            model_name='companypaymentterms',
            name='payment_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Payment Days (in days)'),
        ),
        migrations.AlterField(
            model_name='companypaymentterms',
            name='receiving',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Receiving (in %)'),
        ),
    ]
