# Generated by Django 3.1.2 on 2020-11-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201105_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingbox',
            name='length_unit',
            field=models.CharField(choices=[('cm', 'cm'), ('in', 'in'), ('m', 'm')], default='cm', max_length=20, verbose_name='Length Unit'),
        ),
    ]
