# Generated by Django 3.1.1 on 2020-11-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20201117_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companypaymentterms',
            unique_together=set(),
        ),
    ]
