# Generated by Django 3.1.1 on 2020-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20201005_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='invitation_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
