# Generated by Django 3.1.1 on 2020-11-20 12:42

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20201117_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Contract Title')),
                ('file', models.CharField(max_length=500, verbose_name='Contract File')),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_member', to='company.member')),
                ('companytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companytype')),
                ('partner_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_member', to='company.member')),
                ('paymentterms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companypaymentterms')),
            ],
            options={
                'verbose_name_plural': 'Company Taxes',
            },
        ),
    ]
