# Generated by Django 3.1.1 on 2020-10-07 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_member_invitation_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
