# Generated by Django 3.1 on 2020-10-11 13:36

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_auto_20201001_0943'),
        ('company', '0007_member_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companytype_company', to='setting.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companytype_company', to='company.company')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companytype_partner', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Company Types',
            },
        ),
    ]
