# Generated by Django 3.1 on 2020-10-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_companypaymentterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypaymentterms',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
