# Generated by Django 3.1.1 on 2020-11-27 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0003_auto_20201110_1022"),
        ("company", "0009_auto_20201126_1054"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyproduct",
            options={"verbose_name_plural": "Company Products"},
        ),
        migrations.AlterModelOptions(
            name="componentprice",
            options={"verbose_name_plural": "Component Prices"},
        ),
        migrations.RemoveField(
            model_name="componentgoldensample", name="company"
        ),
        migrations.AddField(
            model_name="componentgoldensample",
            name="componentme",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.componentme",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="componentme",
            name="status",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.PROTECT,
                to="setting.status",
            ),
        ),
    ]
