# Generated by Django 3.1 on 2020-10-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_companypaymentterms_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypaymentterms',
            name='user',
        ),
    ]
