# Generated by Django 3.1.1 on 2020-11-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0003_auto_20201110_1022"),
        ("company", "0010_auto_20201127_0953"),
    ]

    operations = []
