# Generated by Django 3.1 on 2020-10-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Bank Name'),
        ),
    ]
