# Generated by Django 3.1.1 on 2020-11-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20201127_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentme',
            old_name='product',
            new_name='component',
        ),
    ]
