# Generated by Django 3.1.1 on 2020-12-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20201127_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyorderproduct',
            name='componentprice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.componentprice'),
        ),
        migrations.AddField(
            model_name='companyorderproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
