# Generated by Django 3.1 on 2020-10-13 08:10

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20201012_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('address2', models.CharField(blank=True, max_length=200, verbose_name='Apartment, suite, etc.')),
                ('zip', models.CharField(blank=True, max_length=200, verbose_name='Postal/zip code')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='City/town')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='Region/province')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('name', models.CharField(max_length=200, verbose_name='Bank Name')),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
