# Generated by Django 3.1.1 on 2020-12-02 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20201201_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyorderproduct',
            name='companyorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to='company.companyorder'),
        ),
    ]
