# Generated by Django 3.1 on 2020-10-13 09:29

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_measurement.models
import measurement.measures.volume


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Location Name'),
        ),
        migrations.CreateModel(
            name='PackingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Location Name')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Length')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Width')),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Depth')),
                ('cbm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cubic Metres')),
                ('length_unit', models.CharField(choices=[('cm', 'cm'), ('in', 'in')], default='cm', max_length=20, verbose_name='Length Unit')),
                ('weight', django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Packing Boxes',
            },
        ),
    ]
