# Generated by Django 3.1 on 2020-10-13 09:50

from django.db import migrations
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20201013_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingbox',
            name='weight',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass),
        ),
    ]
