# Generated by Django 3.1 on 2020-10-13 13:53

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20201013_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypaymentterms',
            name='title',
            field=models.CharField(max_length=200, verbose_name='PaymentTerms Title'),
        ),
        migrations.AlterField(
            model_name='packingbox',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Packing Name'),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_country', django_countries.fields.CountryField(max_length=2)),
                ('to_country', django_countries.fields.CountryField(max_length=2)),
                ('custom_duty', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Custom Duty')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='VAT')),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Company Taxes',
            },
        ),
        migrations.CreateModel(
            name='HsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hscode', models.CharField(max_length=200, verbose_name='HS Code')),
                ('material', models.CharField(blank=True, max_length=500, verbose_name='Product Material')),
                ('use', models.CharField(blank=True, max_length=500, verbose_name='Product Use')),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Company HSCodes',
            },
        ),
    ]
