# Generated by Django 3.1.1 on 2020-12-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20201205_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='company.company'),
        ),
        migrations.AlterField(
            model_name='companyorderpaymentpaid',
            name='companyorderpayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderpaymentpaid', to='company.companyorderpayment'),
        ),
    ]
