# Generated by Django 3.1.1 on 2020-12-08 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201125_0937'),
        ('company', '0017_auto_20201207_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontract',
            name='companytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contracts', to='company.companytype'),
        ),
        migrations.AlterField(
            model_name='companycredential',
            name='companytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_credentials', to='company.companytype'),
        ),
        migrations.AlterField(
            model_name='companyinventory',
            name='companyproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_inventories', to='company.companyproduct'),
        ),
        migrations.AlterField(
            model_name='companyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_products', to='product.product'),
        ),
        migrations.AlterField(
            model_name='componentgoldensample',
            name='componentme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golden_samples', to='company.componentme'),
        ),
        migrations.AlterField(
            model_name='componentprice',
            name='componentgoldensample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_prices', to='company.componentgoldensample'),
        ),
    ]
