# Generated by Django 3.1 on 2020-10-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20201013_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')], default='g', max_length=20, verbose_name='Weight Unit'),
        ),
    ]
