# Generated by Django 3.1.1 on 2020-12-15 08:01

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201125_0937'),
        ('company', '0018_auto_20201208_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_units', models.PositiveIntegerField()),
                ('x_units_used', models.PositiveIntegerField(default=0)),
                ('no_of_layers', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('companytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_mold', to='company.companytype')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Company Mold',
            },
        ),
    ]
