# Generated by Django 3.1.1 on 2020-12-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_mold'),
        ('company', '0021_auto_20201215_1031'),
    ]

    operations = [
    ]
