# Generated by Django 3.1.1 on 2020-12-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20201217_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mold',
        ),
    ]
