# Generated by Django 3.1.1 on 2020-12-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_companytype_is_active'),
        ('company', '0025_delete_mold'),
    ]

    operations = [
    ]
