# Generated by Django 3.1.1 on 2020-12-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_merge_20201222_0834'),
        ('company', '0026_merge_20201221_0744'),
    ]

    operations = [
    ]
