# Generated by Django 3.1.1 on 2021-02-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_merge_20201223_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentme',
            name='companytype',
        ),
        migrations.RemoveField(
            model_name='componentme',
            name='component',
        ),
        migrations.RemoveField(
            model_name='componentme',
            name='status',
        ),
    ]
