# Generated by Django 3.1 on 2020-10-14 12:38

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_measurement.models
import measurement.measures.mass
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('setting', '0003_auto_20201001_0943'),
        ('company', '0018_auto_20201014_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_component', models.BooleanField(default=False, verbose_name='Is Component')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('sku', models.CharField(blank=True, max_length=200, verbose_name='SKU')),
                ('ean', models.CharField(blank=True, max_length=200, verbose_name='EAN')),
                ('model_number', models.CharField(blank=True, max_length=200, verbose_name='Model Number')),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=200, verbose_name='Manufacturer Part Number')),
                ('type', models.CharField(blank=True, max_length=200, verbose_name='Product Type')),
                ('series', models.CharField(blank=True, max_length=200, verbose_name='Product Series')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Length')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Width')),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Depth')),
                ('length_unit', models.CharField(choices=[('cm', 'cm'), ('in', 'in')], default='cm', max_length=20, verbose_name='Length Unit')),
                ('weight', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass)),
                ('bullet_points', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('hscode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.hscode')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.status')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
