# Generated by Django 3.1 on 2020-10-31 09:53

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_measurement.models
import measurement.measures.mass
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('company', '0001_initial'),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('sku', models.CharField(blank=True, max_length=200, verbose_name='SKU')),
                ('ean', models.CharField(blank=True, max_length=200, verbose_name='EAN')),
                ('model_number', models.CharField(blank=True, max_length=200, verbose_name='Model Number')),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=200, verbose_name='Manufacturer Part Number')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Length')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Width')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Depth')),
                ('length_unit', models.CharField(blank=True, choices=[('cm', 'cm'), ('in', 'in')], default='cm', max_length=20, verbose_name='Length Unit')),
                ('weight', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Option Name')),
                ('value', models.CharField(max_length=200, verbose_name='Option Value')),
            ],
            options={
                'verbose_name_plural': 'Product Options',
            },
        ),
        migrations.CreateModel(
            name='ProductVariationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('productoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productoption')),
            ],
            options={
                'verbose_name_plural': 'Product Options',
            },
        ),
        migrations.CreateModel(
            name='ProductParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_component', models.BooleanField(default=False, verbose_name='Is Component')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('type', models.CharField(blank=True, max_length=200, verbose_name='Product Type')),
                ('series', models.CharField(blank=True, max_length=200, verbose_name='Product Series')),
                ('hscode', models.CharField(blank=True, max_length=200, verbose_name='Product HsCode')),
                ('sku', models.CharField(blank=True, max_length=200, verbose_name='SKU')),
                ('bullet_points', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.status')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Products Parent',
            },
        ),
        migrations.AddField(
            model_name='productoption',
            name='productparent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productparent'),
        ),
        migrations.AddField(
            model_name='product',
            name='productparent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productparent'),
        ),
    ]
