# Generated by Django 3.1.1 on 2020-11-10 09:33

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('setting', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='productparent',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.status'),
        ),
        migrations.AddField(
            model_name='productparent',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='productparent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productparent'),
        ),
        migrations.AddField(
            model_name='product',
            name='productparent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productparent'),
        ),
    ]
