# Generated by Django 3.1 on 2020-10-14 13:35

from django.db import migrations, models
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_unit',
            field=models.CharField(blank=True, choices=[('cm', 'cm'), ('in', 'in')], default='cm', max_length=20, verbose_name='Length Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Width'),
        ),
    ]
