# Generated by Django 3.1.2 on 2020-11-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Manufacturer Part Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Model Number'),
        ),
    ]
