# Generated by Django 3.1 on 2020-10-14 13:38

from django.db import migrations
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201014_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True),
        ),
    ]
