# Generated by Django 3.1.1 on 2020-11-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201110_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer_part_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Manufacturer Part Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Model Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productparent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productparent'),
        ),
        migrations.AlterField(
            model_name='productparent',
            name='sku',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='SKU'),
        ),
    ]
