# Generated by Django 3.1.1 on 2020-11-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201119_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparent',
            name='sku',
            field=models.CharField(blank=True, max_length=200, verbose_name='SKU'),
        ),
    ]
