# Generated by Django 3.1 on 2020-10-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("product", "0004_auto_20201015_1436")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="hscode",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Product HsCode"
            ),
        )
    ]
