# Generated by Django 3.1.1 on 2020-11-21 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companycontract'),
        ('product', '0005_auto_20201120_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
            preserve_default=False,
        ),
    ]
