# Generated by Django 3.1 on 2020-10-20 13:45

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0018_auto_20201014_1238"),
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("setting", "0003_auto_20201001_0943"),
        ("product", "0005_auto_20201015_1707"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Option Name"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=200, verbose_name="Option Value"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Product Options"},
        ),
        migrations.RemoveField(model_name="product", name="bullet_points"),
        migrations.RemoveField(model_name="product", name="company"),
        migrations.RemoveField(model_name="product", name="description"),
        migrations.RemoveField(model_name="product", name="hscode"),
        migrations.RemoveField(model_name="product", name="is_component"),
        migrations.RemoveField(model_name="product", name="series"),
        migrations.RemoveField(model_name="product", name="status"),
        migrations.RemoveField(model_name="product", name="tags"),
        migrations.RemoveField(model_name="product", name="title"),
        migrations.RemoveField(model_name="product", name="type"),
        migrations.CreateModel(
            name="ProductVariationOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "productoption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productoption",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Product Options"},
        ),
        migrations.CreateModel(
            name="ProductParent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_component",
                    models.BooleanField(
                        default=False, verbose_name="Is Component"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="Title"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Product Type"
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Product Series",
                    ),
                ),
                (
                    "hscode",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Product HsCode",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SKU"
                    ),
                ),
                ("bullet_points", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "extra_data",
                    django.contrib.postgres.fields.hstore.HStoreField(
                        blank=True, null=True
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="company.company",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default="Active",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="setting.status",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Products Parent"},
        ),
        migrations.AddField(
            model_name="productoption",
            name="productparent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productparent",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="productparent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productparent",
            ),
            preserve_default=False,
        ),
    ]
