# Generated by Django 3.1 on 2020-10-21 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_auto_20201001_0943'),
        ('product', '0006_auto_20201020_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparent',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.status'),
        ),
    ]
