# Generated by Django 3.1.1 on 2020-11-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20201123_1454'),
        ('product', '0006_image_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcomponents_component', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcomponents_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productpackingbox',
            name='packingbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packingboxs', to='company.packingbox'),
        ),
        migrations.AlterField(
            model_name='productpackingbox',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packingboxs', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productrrp',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rrps', to='product.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productrrp',
            unique_together={('product', 'country')},
        ),
    ]
