# Generated by Django 3.1 on 2020-10-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201021_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='dddd', max_length=500, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
