# Generated by Django 3.1.1 on 2021-01-28 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_auto_20210122_1602'),
        ('company', '0027_merge_20201223_0931'),
        ('product', '0009_productparent_model_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productparent',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='productparent',
        ),
        migrations.AddField(
            model_name='product',
            name='bullet_points',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hscode',
            field=models.CharField(blank=True, max_length=200, verbose_name='Product HsCode'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_component',
            field=models.BooleanField(default=False, verbose_name='Is Component'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_parent', to='product.product', verbose_name='Select Parent'),
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.CharField(blank=True, max_length=200, verbose_name='Product Series'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='setting.status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoption',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductParent',
        ),
    ]
