# Generated by Django 3.1.1 on 2021-02-01 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_auto_20210122_1602'),
        ('product', '0010_auto_20210128_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=1, max_digits=5)),
                ('revision_history', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('status', models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='setting.status')),
            ],
            options={
                'verbose_name_plural': 'Component MEs',
            },
        ),
    ]
