# Generated by Django 3.1.1 on 2021-02-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_productcomponent_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariationoption',
            options={'verbose_name_plural': 'Product Variation Options'},
        ),
    ]
