# Generated by Django 3.1.1 on 2021-02-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210202_0714'),
        ('product', '0013_auto_20210202_0506'),
    ]

    operations = [
    ]
