# Generated by Django 3.1.1 on 2020-10-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20200930_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='paymentterms',
            options={'verbose_name_plural': 'PaymentTerms'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sv',
            field=models.CharField(max_length=200, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='status',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Status Name'),
        ),
        migrations.AddField(
            model_name='status',
            name='name_sv',
            field=models.CharField(max_length=200, null=True, verbose_name='Status Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category Rule'),
        ),
        migrations.AlterField(
            model_name='paymentterms',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='PaymentTerms Title'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Status Name'),
        ),
    ]
