# Generated by Django 3.1.1 on 2020-11-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20201110_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sv',
            field=models.CharField(max_length=200, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='status',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Status Name'),
        ),
        migrations.AddField(
            model_name='status',
            name='name_sv',
            field=models.CharField(max_length=200, null=True, verbose_name='Status Name'),
        ),
    ]
