# Generated by Django 3.1.1 on 2020-12-17 08:52

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_category_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTermName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Delivery Terms Title')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Delivery Terms Code')),
                ('detail', models.TextField(blank=True)),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Terms Name',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTermService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Delivery Terms Title')),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Terms Name',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_pays', models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=20, verbose_name='Who pays for the service')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.deliverytermservice')),
                ('term_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setting.deliverytermname')),
            ],
            options={
                'verbose_name_plural': 'Delivery Terms',
            },
        ),
    ]
