# Generated by Django 3.1.1 on 2020-12-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_auto_20201217_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryterms',
            old_name='term_name',
            new_name='deliverytermname',
        ),
        migrations.RemoveField(
            model_name='deliveryterms',
            name='service',
        ),
        migrations.AddField(
            model_name='deliveryterms',
            name='service_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeliveryTermService',
        ),
    ]
