# Generated by Django 3.1.1 on 2020-12-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_auto_20201217_1108'),
        ('setting', '0006_category_is_sales_channel_category'),
    ]

    operations = [
    ]
