# Generated by Django 3.1.1 on 2021-01-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_logisticleadtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logisticleadtime',
            options={'verbose_name_plural': 'Logistic Lead Time'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='logisticleadtime',
            name='title',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Logistic Title'),
        ),
    ]
