# Generated by Django 3.1.1 on 2021-02-26 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0029_auto_20210201_0811'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonMarketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('marketplaceId', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AmazonAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_partner_id', models.CharField(max_length=255, null=True)),
                ('mws_auth_token', models.CharField(max_length=255, null=True)),
                ('spapi_oauth_code', models.CharField(max_length=255, null=True)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('refresh_token', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.amazonmarketplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
