# Generated by Django 3.1.1 on 2021-03-04 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0029_auto_20210201_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAccountCredentails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_partner_id', models.CharField(max_length=512, null=True)),
                ('mws_auth_token', models.CharField(max_length=512, null=True)),
                ('spapi_oauth_code', models.CharField(max_length=512, null=True)),
                ('access_token', models.CharField(max_length=512, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('refresh_token', models.CharField(max_length=512, null=True)),
                ('region', models.CharField(choices=[('us_east_1', 'North America'), ('eu_west_1', 'Europe'), ('us_west_2', 'Far East')], default='eu_west_1', max_length=255, verbose_name='Region')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmazonMarketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Name')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('marketplaceId', models.CharField(max_length=255, verbose_name='MarketplaceId')),
                ('region', models.CharField(choices=[('us_east_1', 'North America'), ('eu_west_1', 'Europe'), ('us_west_2', 'Far East')], default='eu_west_1', max_length=255, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='AmazonAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('credentails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.amazonaccountcredentails')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.amazonmarketplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
