# Generated by Django 3.1.1 on 2021-03-01 10:13

import bat.market.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonmarketplace',
            name='file',
            field=models.FileField(null=True, upload_to=bat.market.models.file_name, verbose_name='File'),
        ),
        migrations.AddField(
            model_name='amazonmarketplace',
            name='region',
            field=models.CharField(choices=[('us-east-1', 'North America'), ('eu-west-1', 'Europe'), ('us-west-2', 'Far East')], default='eu-west-1', max_length=255, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='amazonmarketplace',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='amazonmarketplace',
            name='marketplaceId',
            field=models.CharField(max_length=255, verbose_name='MarketplaceId'),
        ),
        migrations.AlterField(
            model_name='amazonmarketplace',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
