# Generated by Django 3.1.1 on 2021-03-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210301_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonmarketplace',
            name='file',
        ),
    ]
