# Generated by Django 3.1.1 on 2021-03-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210325_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorderitem',
            name='item_shipment_id',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='amazonorderitem',
            unique_together={('amazonorder', 'item_id', 'item_shipment_id')},
        ),
    ]
