# Generated by Django 3.1.1 on 2021-03-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_amazonmarketplace_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonaccounts',
            name='access_token',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='amazonaccounts',
            name='mws_auth_token',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='amazonaccounts',
            name='refresh_token',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='amazonaccounts',
            name='selling_partner_id',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='amazonaccounts',
            name='spapi_oauth_code',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='amazonmarketplace',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Name'),
        ),
    ]
