# Generated by Django 3.1.1 on 2021-03-04 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_auto_20210201_0811'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0005_auto_20210304_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonaccounts',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='amazonaccounts',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='amazonaccounts',
            name='mws_auth_token',
        ),
        migrations.RemoveField(
            model_name='amazonaccounts',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='amazonaccounts',
            name='selling_partner_id',
        ),
        migrations.RemoveField(
            model_name='amazonaccounts',
            name='spapi_oauth_code',
        ),
        migrations.AlterField(
            model_name='amazonmarketplace',
            name='region',
            field=models.CharField(choices=[('us_east_1', 'North America'), ('eu_west_1', 'Europe'), ('us_west_2', 'Far East')], default='eu_west_1', max_length=255, verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='AmazonAccountCredentails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_partner_id', models.CharField(max_length=512, null=True)),
                ('mws_auth_token', models.CharField(max_length=512, null=True)),
                ('spapi_oauth_code', models.CharField(max_length=512, null=True)),
                ('access_token', models.CharField(max_length=512, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('refresh_token', models.CharField(max_length=512, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='amazonaccounts',
            name='credentails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.amazonaccountcredentails'),
        ),
    ]
