# Generated by Django 3.1.1 on 2021-03-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20210326_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonmarketplace',
            name='name',
            field=models.CharField(default=1, max_length=512, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
