# Generated by Django 3.1.1 on 2021-03-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20210304_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonaccountcredentails',
            name='region',
            field=models.CharField(choices=[('us_east_1', 'North America'), ('eu_west_1', 'Europe'), ('us_west_2', 'Far East')], default='eu_west_1', max_length=255, verbose_name='Region'),
        ),
    ]
