# Generated by Django 3.1.1 on 2021-04-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20210330_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonorder',
            name='order_id',
            field=models.CharField(max_length=300),
        ),
    ]
