# Generated by Django 3.1.1 on 2021-04-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20210402_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonmarketplace',
            name='sales_channel_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Sales Channel Name'),
            preserve_default=False,
        ),
    ]
