# Generated by Django 3.1.1 on 2021-04-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_amazonmarketplace_sales_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonmarketplace',
            name='vat_tax_included',
            field=models.BooleanField(default=True),
        ),
    ]
