# Generated by Django 3.1.1 on 2021-04-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_amazonmarketplace_vat_tax_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonaccounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
