# Generated by Django 3.1.1 on 2021-04-20 07:55

import bat.globalprop.validator.validator
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_amazonaccounts_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('address2', models.CharField(blank=True, max_length=200, verbose_name='Apartment, suite, etc.')),
                ('zip', models.CharField(blank=True, max_length=200, verbose_name='Postal/zip code')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='City/town')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='Region/province')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('store_name', models.CharField(max_length=200, verbose_name='Store Name')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[bat.globalprop.validator.validator.phone_validator()], verbose_name='Phone Number')),
                ('organization_number', models.CharField(blank=True, help_text='Company register number for the marketplace company.', max_length=200, verbose_name='Organization number')),
                ('vat_number', models.CharField(blank=True, help_text='Company VAT number for the marketplace company.', max_length=200, verbose_name='VAT number')),
                ('extra_data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Amazon Companies',
            },
        ),
    ]
