# Generated by Django 3.1.1 on 2021-04-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_amazoncompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazoncompany',
            name='amazonaccounts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.amazonaccounts', verbose_name='Select Amazon Account'),
            preserve_default=False,
        ),
    ]
