# Generated by Django 3.1.1 on 2021-04-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_amazoncompany_amazonaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazoncompany',
            name='amazonaccounts',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.amazonaccounts', verbose_name='Select Amazon Account'),
        ),
    ]
