# Generated by Django 3.1.1 on 2021-04-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20210420_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorder',
            name='amazon_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
