# Generated by Django 3.1.1 on 2021-05-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20210420_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonaccountcredentails',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
    ]
