# Generated by Django 3.1.1 on 2021-05-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_amazonaccountcredentails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonaccountcredentails',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
