# Generated by Django 3.1.1 on 2021-05-20 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_auto_20210201_0811'),
        ('market', '0016_amazonaccountcredentails_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPCProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.BigIntegerField(verbose_name='Profile ID')),
                ('amazonmarketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.amazonmarketplace')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='PPCCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(max_length=1024, verbose_name='Auth Code')),
                ('access_token', models.CharField(max_length=2024, verbose_name='Access Token')),
                ('refresh_token', models.CharField(max_length=2024, verbose_name='Refresh Token')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
