# Generated by Django 3.1.1 on 2021-05-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_ppccredentials_ppcprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppccredentials',
            options={'verbose_name_plural': 'PPC Credentials'},
        ),
        migrations.AlterModelOptions(
            name='ppcprofile',
            options={'verbose_name_plural': 'PPC Profile'},
        ),
    ]
