# Generated by Django 3.1.1 on 2021-05-28 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_auto_20210525_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProductSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amazonproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.amazonproduct', verbose_name='Select Amazon Product')),
            ],
            options={
                'unique_together': {('amazonproduct', 'date')},
            },
        ),
    ]
