# Generated by Django 3.1.1 on 2021-05-31 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_amazonproductsessions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonproductsessions',
            options={'verbose_name_plural': 'Amazon Product Sessions'},
        ),
    ]
