# Generated by Django 3.1.1 on 2021-06-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_auto_20210605_0437'),
        ('market', '0020_auto_20210531_1223'),
    ]

    operations = [
    ]
