# Generated by Django 3.1.1 on 2021-06-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_merge_20210607_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Image url'),
        ),
    ]
