# Generated by Django 3.1.1 on 2021-06-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_merge_20210607_0557'),
        ('market', '0022_amazonproduct_thumbnail'),
    ]

    operations = [
    ]
