# Generated by Django 3.1.1 on 2021-06-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_merge_20210607_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonaccounts',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
