CM = "cm"
IN = "in"
LENGTH_UNIT_TYPE = ((CM, "cm"), (IN, "in"))

PRODUCT_PARENT_STATUS = "Basic"
PRODUCT_STATUS_ACTIVE = "Active"
PRODUCT_STATUS_ARCHIVE = "Archive"
PRODUCT_STATUS_DRAFT = "Draft"

PRODUCT_STATUS_CHOICE = [PRODUCT_STATUS_ACTIVE,
                         PRODUCT_STATUS_ARCHIVE, PRODUCT_STATUS_DRAFT]

PRODUCT_STATUS = {"active": "PRODUCT_STATUS_ACTIVE",
                  "archive": "PRODUCT_STATUS_ARCHIVE",
                  "draft": "PRODUCT_STATUS_DRAFT"}
