
ORDER_PARENT_STATUS = "Order"
ORDER_STATUS_PENDING = "Pending"
ORDER_STATUS_SHIPPED = "Shipped"
ORDER_STATUS_CANCELED = "Canceled"
ORDER_STATUS_INVOICE_UNCONFIRMED = "InvoiceUnconfirmed"
ORDER_STATUS_PARTIALLY_SHIPPED = "PartiallyShipped"
ORDER_STATUS_PENDING_AVAILABILITY = "PendingAvailability"
ORDER_STATUS_UNFULFILLABLE = "Unfulfillable"
ORDER_STATUS_UNSHIPPED = "Unshipped"


AMAZON_ORDER_STATUS_CHOICE = [ORDER_STATUS_PENDING,
                              ORDER_STATUS_SHIPPED,
                              ORDER_STATUS_CANCELED,
                              ORDER_STATUS_INVOICE_UNCONFIRMED,
                              ORDER_STATUS_PARTIALLY_SHIPPED,
                              ORDER_STATUS_PENDING_AVAILABILITY,
                              ORDER_STATUS_UNFULFILLABLE,
                              ORDER_STATUS_UNSHIPPED,
                              ]


NORTH_AMERICA = "us_east_1"
EUROPE = "eu_west_1"
FAR_EAST = "us_west_2"

AMAZON_REGIONS_CHOICES = (
    (NORTH_AMERICA, "North America"),
    (EUROPE, "Europe"),
    (FAR_EAST, "Far East"),
)

MARKETPLACE_STATUS_ACTIVE = "active"
MARKETPLACE_STATUS_INACTIVE = "inactive"


MARKETPLACE_CODES = {
    "A2VIGQ35RCS4UG": "AE",
    "A1PA6795UKMFR9": "DE",
    "ARBP9OOSHTCHU": "EG",
    "A1RKKUPIHCS9HS": "ES",
    "A13V1IB3VIYZZH": "FR",
    "A21TJRUUN4KGV": "IN",
    "APJ6JRA9NG5V4": "IT",
    "A1805IZSGTT6HS": "NL",
    "A17E79C6D8DWNP": "SA",
    "A2NODRKZP88ZB9": "SE",
    "A33AVAJ2PDY3EV": "TR",
    "A1F83G8C2ARO7P": "GB",
    "A39IBJ37TRP1C6": "AU",
    "A1VC38T7YXB528": "JP",
    "A19VAU5U5O7RUS": "SG",
    "ATVPDKIKX0DER": "US",
    "A2Q3Y263D00KWC": "BR",
    "A2EUQ1WTGCTBG2": "CA",
    "A1AM78C64UM0Y8": "MX",
}

