# Generated by Django 3.1.1 on 2021-05-11 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0012_auto_20210122_1602'),
        ('market', '0016_amazonaccountcredentails_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amazonmarketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.amazonmarketplace')),
            ],
            options={
                'unique_together': {('amazonmarketplace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('amazonproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.amazonproduct', verbose_name='Select Amazon Product')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordtracking.keyword', verbose_name='Select Keyword')),
                ('status', models.ForeignKey(default='Active', on_delete=django.db.models.deletion.PROTECT, to='setting.status')),
            ],
            options={
                'unique_together': {('amazonproduct', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='ProductKeywordRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BooleanField(default=False)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('page', models.PositiveIntegerField(default=0)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('visibility_score', models.DecimalField(decimal_places=2, default='0.0', max_digits=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveIntegerField(default=0)),
                ('productkeyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywordtracking.productkeyword', verbose_name='Select Product Keyword')),
            ],
            options={
                'unique_together': {('productkeyword', 'date')},
            },
        ),
    ]
