# Generated by Django 3.1.1 on 2021-05-11 15:00

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordtracking', '0002_auto_20210511_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productkeywordrank',
            old_name='status',
            new_name='scrap_status',
        ),
        migrations.AddField(
            model_name='productkeywordrank',
            name='extra_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
