# Generated by Django 3.1.1 on 2021-05-17 12:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_amazonaccountcredentails_email_verified'),
        ('keywordtracking', '0004_auto_20210514_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('asin_1', models.CharField(blank=True, max_length=50)),
                ('asin_2', models.CharField(blank=True, max_length=50)),
                ('asin_3', models.CharField(blank=True, max_length=50)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amazonmarketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.amazonmarketplace')),
            ],
            options={
                'unique_together': {('amazonmarketplace', 'name')},
            },
        ),
    ]
