# Generated by Django 3.1.1 on 2021-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordtracking', '0005_globalkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalkeyword',
            name='department',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='globalkeyword',
            unique_together={('department', 'name')},
        ),
        migrations.RemoveField(
            model_name='globalkeyword',
            name='amazonmarketplace',
        ),
    ]
