# Generated by Django 3.1.1 on 2021-05-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordtracking', '0006_auto_20210517_1316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='globalkeyword',
            unique_together=set(),
        ),
    ]
