# Generated by Django 3.1.1 on 2021-05-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordtracking', '0008_productkeywordrank_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productkeywordrank',
            name='company',
        ),
    ]
