# Generated by Django 3.1.1 on 2021-06-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordtracking', '0010_productkeywordrank_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalkeyword',
            name='asin_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='globalkeyword',
            name='asin_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='globalkeyword',
            name='asin_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
