# Generated by Django 3.1.1 on 2021-06-05 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keywordtracking', '0010_productkeywordrank_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkeyword',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
