# Generated by Django 3.1.1 on 2021-06-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordtracking', '0011_auto_20210605_0437'),
        ('keywordtracking', '0011_auto_20210605_1520'),
    ]

    operations = [
    ]
