# Generated by Django 3.1.1 on 2021-06-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordtracking', '0012_merge_20210607_0630'),
        ('keywordtracking', '0012_merge_20210607_0556'),
    ]

    operations = [
    ]
