# Generated by Django 3.1.1 on 2021-06-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordtracking', '0014_auto_20210611_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkeywordrank',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
