# Generated by Django 3.1.1 on 2021-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordtracking', '0015_auto_20210611_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkeywordrank',
            name='frequency',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
