# Generated by Django 3.1.1 on 2021-06-11 10:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordtracking', '0016_auto_20210611_0844'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='globalkeyword',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['department', 'name'], name='keywordtrac_departm_e3b160_btree'),
        ),
    ]
