# Generated by Django 3.1.1 on 2021-06-11 11:10

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywordtracking', '0017_auto_20210611_1034'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='keyword',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['name'], name='keywordtrac_name_4d1064_btree'),
        ),
    ]
