# Generated by Django 3.1.1 on 2020-09-28 09:44

import bat.globalprop.validator.validator
import bat.users.models
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wechat',
        ),
        migrations.AddField(
            model_name='user',
            name='extra_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=50, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Time Zone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[bat.globalprop.validator.validator.phone_validator()], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=bat.users.models.profilepic_name, verbose_name='Profile Picture'),
        ),
    ]
