# Generated by Django 3.1.1 on 2020-09-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200928_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sv', 'Swedish')], max_length=50, verbose_name='Language'),
        ),
    ]
