# Generated by Django 3.1.1 on 2020-12-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201201_0907'),
        ('users', '0003_userloginactivity'),
    ]

    operations = [
    ]
