# Generated by Django 3.1.1 on 2021-01-27 08:41

import bat.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201228_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='por_file',
            field=models.FileField(blank=True, upload_to=bat.users.models.por_file_name, verbose_name='File'),
        ),
    ]
